/**
 * Canonical regex sources generated from the guard-core spec 4.0.2 reference
 * (guard_core/handlers/_suspatterns_*.py). The strings are byte-identical to
 * the reference constants, including Python raw-string backslash-quotes;
 * they key the structural matchers and validators and are carried verbatim
 * on threats. Regenerate via the reference when the spec moves.
 */

export const _SELECT_FROM_RE = "(?i)\\bSELECT\\b(?:(?!\\bSELECT\\b)[\\w\\s,\\*().])*?\\bFROM\\b";
export const _SELECT_STAR_RE = "(?i)SELECT\\s+\\*";
export const _WHERE_CLAUSE_RE = "(?i)\\bWHERE\\s+[\\w.\"]+\\s*(?:=|<|>|<=|>=|LIKE|IN)\\b";
export const _SQLI_TAUTOLOGY_RE = "(?i)\\b(?:OR|AND)\\s*(\\d+|'[^']*'|\\\"[^\\\"]*\\\"|[@:$][A-Za-z_]\\w*)\\s*=\\s*\\1\\b";
export const _PATH_ONLY_CHAR_RE = "[\\w.\\-~%]";
export const _PATH_ONLY_SEP_RE = "[/\\\\]";
export const _PATH_ONLY_PREFIX_RE = "\\A[/\\\\]?(?:[\\w.\\-~%]+[/\\\\])*";
export const _PATH_ONLY_SUFFIX_RE = "(?:[/\\\\][\\w.\\-~%]*)*(?:\\?\\S*)?\\s*\\Z";
export const _SENSITIVE_SOURCE_EXTENSION_PATH_RE = "\\A[/\\\\]?(?:[\\w.\\-~%]+[/\\\\])*[\\w.\\-~%]*\\.(?:ts|tsx|jsx|py|rb|java|go|rs|php|pl|sh|sql)(?:[/\\\\][\\w.\\-~%]*)*(?:\\?\\S*)?\\s*\\Z";
export const _RECON_EXTENSION_PATH_RE = "\\A[/\\\\]?(?:[\\w.\\-~%]+[/\\\\])*[\\w.\\-~%]*\\.(?:asp|aspx|jsp|jsa|jhtml|shtml|cfm|cgi|do|action|lua|inc|woa|nsf|esp)(?:[/\\\\][\\w.\\-~%]*)*(?:\\?\\S*)?\\s*\\Z";
export const _ATTACK_REPORT_LEXICON_RE = "\\b(?:scan(?:ner|ning|ned|s)?|attack(?:er|ers|ed|s)?|attempt(?:ed|s)?|exploit(?:ation|ed|s|ing|kit)?|prob(?:e|ed|es|ing)|malicious|intrusion(?:s)?|botnet(?:s)?|honeypot(?:s)?|brute[- ]force|credential[- ]stuffing|threat feed|vulnerabilit(?:y|ies)|hostile|recon(?:naissance)?|spoofed referer|bad actor(?:s)?|WAF|IDS|SOC|pentest(?:ing)?|blocked|flagged|triggered|denied|enumerat(?:e|ed|ing)|suspicious)\\b";
export const _SINGLE_LINE_PREFIX_RE = "\\A(?:(?!\\n).)*";
export const _SINGLE_LINE_SUFFIX_RE = "(?:[&#;,\\\"'<>]|\\s*\\Z)";
export const _TOP_LEVEL_PATH_PREFIX_RE = "\\A[/\\\\]?";
export const _TERMINAL_PATH_SUFFIX_RE = "(?:[/\\\\])?(?:\\?\\S*)?\\s*\\Z";
export const _LDAP_ATTR_DESC_RE = "(?::)?(?:[a-zA-Z][\\w.-]*|\\d+(?:\\.\\d+)*)(?:;[\\w.-]+)*(?::[\\w.-]+)*\\s*";
export const _LDAP_ATTR_EXTENSIBLE_MATCH_RE = "(?::)?(?:[a-zA-Z][\\w.-]*|\\d+(?:\\.\\d+)*)(?:;[\\w.-]+)*(?::[\\w.-]+)*\\s*:?=";
export const _LDAP_WILDCARD_CHAIN_RE = "\\*\\)[|&]?\\(+\\s*(?::)?(?:[a-zA-Z][\\w.-]*|\\d+(?:\\.\\d+)*)(?:;[\\w.-]+)*(?::[\\w.-]+)*\\s*:?=";
export const _LDAP_BREAKOUT_WILDCARD_CLAUSE_END_RE = "=[^()]+\\*\\s*\\Z";
export const _LDAP_BREAKOUT_ATTACK_TOKEN_RE = "\\*|\\(\\s*[&|!]|\\x00|\\(\\s*\\(|~=|>=|<=";
export const _LDAP_FILTER_EXPRESSION_STRUCTURE_RE = "[()\\\"'\\n]";
export const _PROTO_POLLUTION_PROTOTYPE_ASSIGN_RE = "Object\\.prototype\\.[A-Za-z_$][\\w$]*\\s*=(?!=)";
export const _PROTO_POLLUTION_SET_PROTOTYPE_OF_RE = "\\b(?:Object|Reflect)\\.setPrototypeOf\\s*\\(";
export const _XML_XXE_PUBLIC_EXTERNAL_DTD_RE = "<!DOCTYPE[^>\\[]+PUBLIC[^>\\[]+[\\\"']https?://(?!(?:www\\.)?w3\\.org/)[^\\\"'>]+[\\\"'][^>\\[]*>";
export const _XSS_JS_SCHEME_CTRL_CHAR_RE = "j[\\t\\r\\n]*a[\\t\\r\\n]*v[\\t\\r\\n]*a[\\t\\r\\n]*s[\\t\\r\\n]*c[\\t\\r\\n]*r[\\t\\r\\n]*i[\\t\\r\\n]*p[\\t\\r\\n]*t[\\t\\r\\n]*:\\s*[^\\s]+";
export const _FILE_INCLUSION_JSON_VALUE_RE = "[\\\"'](?:template|include|tpl|module|layout)[\\\"']\\s*:\\s*[\\\"'](?:https?|ftp)://[^\\s'\\\"<>]+/[^\\s'\\\"<>/]*\\.(?:phtml|php[3-5]?|phar|jsp|aspx?|cgi|pl|py|sh|txt|inc)(?![a-zA-Z0-9])[\\\"']";
export const _SSRF_BARE_METADATA_ALIAS_RE = "://(?:metadata|instance-data)(?::\\d+)?(?:/|\\s|$)";
export const _CMD_INJECTION_NODE_CHILD_PROCESS_RE = "(?:require\\(\\s*[\\\"']child_process[\\\"']\\s*\\)|child_process)\\s*\\.\\s*(?:execSync|spawnSync|spawn|fork)\\s*\\(";
export const _CMD_INJECTION_PHP_ASSERT_VARIABLE_RE = "\\bassert\\s*\\(\\s*\\$";
export const _CMD_INJECTION_PYTHON_EXEC_FAMILY_RE = "\\bos\\.exec(?:l|le|lp|lpe|v|ve|vp|vpe)\\s*\\(";
export const _JS_DYNAMIC_EVAL_FUNCTION_CTOR_RE = "\\b(?:new\\s+)?Function\\s*\\(\\s*[\\\"']";
export const _JS_DYNAMIC_EVAL_BRACKET_RE = "\\[\\s*[\\\"']eval[\\\"']\\s*\\]\\s*\\(\\s*[\\\"']";
export const _JS_DYNAMIC_EVAL_CTOR_GADGET_RE = "(?:\\.\\s*constructor|\\[\\s*[\\\"']constructor[\\\"']\\s*\\])\\s*(?:\\.\\s*constructor|\\[\\s*[\\\"']constructor[\\\"']\\s*\\])\\s*\\(\\s*[\\\"']";
export const _JS_DYNAMIC_EVAL_TIMER_STRING_ARG_RE = "\\b(?:setTimeout|setInterval)\\s*\\(\\s*[\\\"']";
export const _FILE_INCLUSION_HOST_LABEL_RE = "[0-9a-zA-Z](?:[-\\w]*[0-9a-zA-Z])?";
export const _FILE_INCLUSION_BARE_HOST_RE = "(?:(?<!:)\\/\\/[0-9a-zA-Z](?:[-\\w]*[0-9a-zA-Z])?(?:\\.[0-9a-zA-Z](?:[-\\w]*[0-9a-zA-Z])?)+(:[0-9]+)?(?:\\/?)(?:[a-zA-Z0-9\\-\\.\\?,'/\\\\\\+&amp;%\\$#_]*)?)";
export const _HTTP_SPLIT_CRLF_RE = "[\\r\\n][^\\S\\r\\n]*(?:HTTP\\/[0-9.]+|Location:|Set-Cookie:)";
export const _SQLI_ORDER_BY_TERMINATOR_RE = "(?i)\\bORDER\\s+BY\\s+\\d+\\s*(?:--|#|;|\\)|,|/\\*|\\Z)|(?<=[=?&])ORDER\\s+BY\\s+\\d+\\s*\\n";
export const _SQLI_ORDER_BY_STRONG_RE = "(?i)(?:['\\\")\\d]|/\\*)\\s{0,3}\\bORDER\\s+BY\\s+\\d+|\\bORDER\\s+BY\\s+\\d+\\s*(?:--|#|/\\*)";
export const _SQLI_EXEC_STRONG_RE = "(?i)(?:\\A|[;'\\\"])\\s*EXEC(?:UTE)?\\s+(?:xp_\\w+|sp_\\w+)";
export const _SQLI_COMMENT_TERMINATOR_RE = "'\\s*(?:[\\);]+\\s*)?--|'[\\);]*#(?:\\n|\\Z)";
export const _SQLI_WAITFOR_RE = "(?i)\\bWAITFOR\\s+(?:DELAY|TIME)\\s+'\\d{1,2}:\\d{1,2}:\\d{1,2}(?:\\.\\d+)?'";
export const _PATH_TRAVERSAL_ENCODED_DOT_RE = "(?:%2e%2e|%252e%252e|%uff0e%uff0e|%c0%ae%c0%ae|%e0%40%ae|%c0%ae%e0%80%ae|%25c0%25ae)/";
export const _PATH_TRAVERSAL_SEMICOLON_SEP_RE = "\\.\\.;[^/\\\\]*[/\\\\]";
export const _PATH_TRAVERSAL_DECODED_SHAPE_RE = "\\.\\.[\\\\/]";
export const _CMD_INJECTION_NEWLINE_SHELL_DASH_C_RE = "\\n[^\\S\\r\\n]*(?:[^=\\s;|&]+=[^\\s;|&]+\\s+)*(?:/?(?:[\\w.-]+/)*env\\s+)?/?(?:[\\w.-]+/)*(?:bash|sh|ksh|csh|tsch|zsh|ash)\\s+-c\\b";
export const _CMD_INJECTION_SHELL_DASH_FLAG_RE = "(?:\\A|[;|&])\\s*/?(?:[\\w.-]+/)*(?:env\\s+/?(?:[\\w.-]+/)*)?(?:bash|sh|ksh|csh|tsch|zsh|ash)\\s+-[a-zA-Z]+(?:\\s+(?:'[^']*'|\\\"[^\\\"]*\\\"|[^\\s;|&]+))?(?=\\s*(?:[;|&]|\\Z))";
export const _DIR_TRAVERSAL_ETC_SENSITIVE_RE = "\\A(?:(?!\\n).)*etc/(?:passwd|shadow|group|hosts|motd|issue|mysql/my\\.cnf|ssh/ssh_config)(?:[&#;,\\\"'<>]|\\s*\\Z)";
export const _DIR_TRAVERSAL_WINDOWS_INI_RE = "\\A(?:(?!\\n).)*(?:boot\\.ini|win\\.ini|system\\.ini|config\\.sys)(?:[&#;,\\\"'<>]|\\s*\\Z)";
export const _DIR_TRAVERSAL_PROC_ENVIRON_RE = "\\A(?:(?!\\n).)*proc/self/environ(?:[&#;,\\\"'<>]|\\s*\\Z)";
export const _DIR_TRAVERSAL_VAR_LOG_RE = "\\A(?:(?!\\n).)*var/log/[^\\s/]+(?:[&#;,\\\"'<>]|\\s*\\Z)";
export const _SSTI_HASH_BRACE_SHAPE_RE = "#\\{(?![^\\}]*\\d{4}-\\d{1,2}-\\d{1,2}(?!\\d))(?=[^\\}]*(?:@[\\w.]+@|\\b\\w+\\s*\\(|['\\\"]?\\d+['\\\"]?\\s*[*/%+\\-]\\s*['\\\"]?\\d+['\\\"]?))[^\\}]*\\}";
export const _DESERIALIZATION_JAVA_B64_RE = "(?<![A-Za-z0-9+/])(?-i:rO0AB)";
export const _DESERIALIZATION_DOTNET_B64_RE = "(?<![A-Za-z0-9+/])(?-i:AAEAAAD)";
export const _DESERIALIZATION_PICKLE_B64_RE = "(?<![A-Za-z0-9+/])(?-i:gA[SW]V)";
export const _DESERIALIZATION_RUBY_B64_RE = "(?<![A-Za-z0-9+/])(?-i:BAh[Jv7bV])";
export const _DESERIALIZATION_PICKLE_OS_GLOBAL_RE = "cos\\n";
export const _PICKLE_IDENT_RE = "[A-Za-z_][A-Za-z0-9_]{0,100}";
export const _PICKLE_DOTTED_MODULE_RE = "[A-Za-z_][A-Za-z0-9_]{0,100}(?:\\.[A-Za-z_][A-Za-z0-9_]{0,100}){0,20}";
export const _DESERIALIZATION_PICKLE_GLOBAL_GENERIC_RE = "(c[A-Za-z_][A-Za-z0-9_]{0,100}(?:\\.[A-Za-z_][A-Za-z0-9_]{0,100}){0,20}\\n[A-Za-z_][A-Za-z0-9_]{0,100}\\n)[^ \\t]{0,100}?[Rb]";
export const _LDAP_PAREN_CONJUNCTION_RE = "\\(\\s*[&|]\\s*";
export const _LDAP_WILDCARD_EQUALS_RE = "\\*\\s*\\)+\\s*(?:[|&!]\\s*)?\\(+\\s*(?:[&|!]|(?::)?(?:[a-zA-Z][\\w.-]*|\\d+(?:\\.\\d+)*)(?:;[\\w.-]+)*(?::[\\w.-]+)*\\s*:?=)";
export const _LDAP_PAREN_BREAKOUT_RE = "\\)\\s*\\(\\s*(?:[&|!]|(?::)?(?:[a-zA-Z][\\w.-]*|\\d+(?:\\.\\d+)*)(?:;[\\w.-]+)*(?::[\\w.-]+)*\\s*:?[=~<>])";
export const _LDAP_NULL_BYTE_ATTR_RE = "[a-zA-Z][\\w-]*\\s*=[\\d\\w\\s]*\\*\\)+(?:%00|\\\\u0000|\\\\x00|\\\\0|\\x00)";
export const _LDAP_NULL_BYTE_BARE_RE = "\\*\\)\\)+(?:%00|\\\\u0000|\\\\x00|\\\\0|\\x00)";
export const _LDAP_NULL_BYTE_DECODED_ATTR_RE = "[a-zA-Z][\\w-]*\\s*=[\\d\\w\\s]*\\*\\)+\\x00";
export const _LDAP_NULL_BYTE_DECODED_BARE_RE = "\\*\\)\\)+\\x00";
export const _GLUED_BACKTICK_CANDIDATE_RE = "(?<!`)`(?:[A-Za-z0-9_./~]|\\$[({])(?:[^`\\\\\\n]|\\\\.)*`";
export const _GLUED_DOLLAR_SUBSTITUTION_CANDIDATE_RE = "\\$\\((?:[^()\\\\\\n]|\\\\.)*\\)|\\$\\{(?:[^{}\\\\\\n]|\\\\.)*\\}";
export const _BRACE_EXPANSION_ITEM_RE = "[^{}\\s,:'\\\"][^{},:'\\\"]*";
export const _BRACE_EXPANSION_COMMAND_RE = "(?:\\A|[;&|]\\s*|\\$\\()\\{[^{}\\s,:'\\\"][^{},:'\\\"]*(?:,(?:[^{}\\s,:'\\\"][^{},:'\\\"]*)?)+\\}";
export const _QUOTE_SPLICE_CANDIDATE_RE = "\\w+(?:['\\\"]+\\w+){1,10}";
export const _GLOB_WILDCARD_ATOM_RE = "[A-Za-z0-9_./*?-]*[?*][A-Za-z0-9_./*?-]*";
export const _PY_DANGEROUS_MODULE_RE = "__import__\\(\\s*['\\\"](?:os|subprocess|builtins|importlib)['\\\"]\\s*\\)|\\b(?:os|subprocess|builtins|importlib)\\b";
export const _PY_DANGEROUS_METHOD_RE = "system|popen|exec|eval|call|run|Popen|check_output|check_call";
export const _PY_GETATTR_INDIRECTION_RE = "(?-i:\\bgetattr\\(\\s*(?:__import__\\(\\s*['\\\"](?:os|subprocess|builtins|importlib)['\\\"]\\s*\\)|\\b(?:os|subprocess|builtins|importlib)\\b)\\s*,\\s*['\\\"](?:system|popen|exec|eval|call|run|Popen|check_output|check_call)['\\\"]\\s*\\)\\s*\\()";
export const _PY_VARS_INDIRECTION_RE = "(?-i:\\bvars\\(\\s*(?:__import__\\(\\s*['\\\"](?:os|subprocess|builtins|importlib)['\\\"]\\s*\\)|\\b(?:os|subprocess|builtins|importlib)\\b)\\s*\\)\\s*\\[\\s*['\\\"](?:system|popen|exec|eval|call|run|Popen|check_output|check_call)['\\\"]\\s*\\]\\s*\\()";
export const _BACKTICK_WINDOW_DELIMITER_CHARS = "`'\"\n\r";
export const _SQLI_LOAD_FILE_RE = "(?i)(?:LOAD_FILE\\s*\\([^)]+\\))";
export const _CMD_INJECTION_DOLLAR_SUBSTITUTION_RE = "(?:[;&|]\\s*(?:\\$\\([^)]+\\)|\\$\\{[^}]+\\}))";
export const _TEMPLATE_CURLY_KEYWORD_RE = "\\{\\{\\s*[^\\}]+(?:system|exec|popen|eval|require|include)\\s*\\}\\}";
export const _TEMPLATE_DOLLAR_BRACE_CALL_RE = "\\$\\{[^}]*(?:@[\\w.]+@|\\b\\w+\\s*\\(|\\d+\\s*[*/%+\\-]\\s*\\d+)[^}]*\\}";
export const _TEMPLATE_CURLY_CALL_RE = "\\{\\{(?![^\\}]*\\d{4}-\\d{1,2}-\\d{1,2}(?!\\d))(?=[^\\}]*(?:@[\\w.]+@|\\b\\w+\\(\\s*\\)|['\\\"]?\\d+['\\\"]?\\s*[*/%+\\-]\\s*['\\\"]?\\d+['\\\"]?))[^\\}]*\\}\\}";
export const _TEMPLATE_PERCENT_KEYWORD_RE = "\\{\\%\\s*[^\\%]+(?:system|exec|popen|eval|require|include)\\s*\\%\\}";
export const _TEMPLATE_ASP_KEYWORD_RE = "(?i)<%[=#]?[^%]*(?:system|exec|eval|`|Runtime|IO\\.|File\\.|Dir\\.|\\d+\\s*[-+*/]\\s*\\d+)[^%]*%>";
export const _ATTR_EQUALS_WHITESPACE_RE = "\\s{0,20}";
export const _HTML_TAG_OPEN_RE = "<[A-Za-z/]";
export const _FILE_UPLOAD_NULL_OR_SEPARATOR_TRUNCATION_RE = "(?:%00|\\\\u0000|\\\\x00|\\\\0|\\x00|;)";
export const _FILE_UPLOAD_ATTR_EQUALS_WHITESPACE_RE = "\\s*";
export const _FILE_UPLOAD_FILENAME_EQUALS_RE = "(?:\\A|[;,:\\n])\\s*filename\\s*=\\s*";
export const _FILE_UPLOAD_DOUBLE_EXTENSION_RE = "(?:\\A|[;,:\\n])\\s*filename\\s*=\\s*[\\\"'][^\\\"']*\\.(?:php\\d*|phtml|shtml|asax|ascx|ashx|asmx|aspx|bash|jspx|phar|phps|asa|asp|bat|cer|cfc|cfm|cgi|cmd|exe|hta|jsp|msi|pht|vbe|vbs|war|wsf|js|pl|py|rb|sh|ws)(?![A-Za-z0-9])(?:[^ \\\"'][^\\\"']*)?\\.(?:docx|jpeg|pptx|tiff|webm|webp|xlsx|avi|bmp|doc|gif|ico|jpg|mkv|mov|mp3|mp4|odt|pdf|png|ppt|svg|tif|wav|xls)[\\\"']";
export const _FILE_UPLOAD_TRUNCATION_RE = "(?:\\A|[;,:\\n])\\s*filename\\s*=\\s*[\\\"'][^\\\"']*\\.(?:php\\d*|phtml|shtml|asax|ascx|ashx|asmx|aspx|bash|jspx|phar|phps|asa|asp|bat|cer|cfc|cfm|cgi|cmd|exe|hta|jsp|msi|pht|vbe|vbs|war|wsf|js|pl|py|rb|sh|ws)(?![A-Za-z0-9])(?:(?:%00|\\\\u0000|\\\\x00|\\\\0|\\x00|;)[^\\\"']*|\\.)[\\\"']";
export const _FILE_UPLOAD_DECODED_TRUNCATION_RE = "(?:\\A|[;,:\\n])\\s*filename\\s*=\\s*[\\\"'][^\\\"']*\\.(?:php\\d*|phtml|shtml|asax|ascx|ashx|asmx|aspx|bash|jspx|phar|phps|asa|asp|bat|cer|cfc|cfm|cgi|cmd|exe|hta|jsp|msi|pht|vbe|vbs|war|wsf|js|pl|py|rb|sh|ws)(?![A-Za-z0-9])(?:(?:\\x00|;)[^\\\"']*|\\.)[\\\"']";
export const _FILE_UPLOAD_DANGEROUS_EXTENSION_RE = "(?:\\A|[;,:\\n])\\s*filename\\s*=\\s*[\\\"'][^\\\"']*\\.(?:php\\d*|phtml|shtml|asax|ascx|ashx|asmx|aspx|bash|jspx|phar|phps|asa|asp|bat|cer|cfc|cfm|cgi|cmd|com|exe|hta|jsp|msi|pht|vbe|vbs|war|wsf|js|pl|py|rb|sh|ws)[\\\"']";
export const _FILE_UPLOAD_DANGEROUS_EXT_ALTERNATION = "php\\d*|phtml|shtml|asax|ascx|ashx|asmx|aspx|bash|jspx|phar|phps|asa|asp|bat|cer|cfc|cfm|cgi|cmd|com|exe|hta|jsp|msi|pht|vbe|vbs|war|wsf|js|pl|py|rb|sh|ws";
export const _FILE_UPLOAD_DOUBLE_EXT_ALTERNATION = "php\\d*|phtml|shtml|asax|ascx|ashx|asmx|aspx|bash|jspx|phar|phps|asa|asp|bat|cer|cfc|cfm|cgi|cmd|exe|hta|jsp|msi|pht|vbe|vbs|war|wsf|js|pl|py|rb|sh|ws";
export const _FILE_UPLOAD_BENIGN_TERMINAL_ALTERNATION = "docx|jpeg|pptx|tiff|webm|webp|xlsx|avi|bmp|doc|gif|ico|jpg|mkv|mov|mp3|mp4|odt|pdf|png|ppt|svg|tif|wav|xls";
export const _LOG4SHELL_JNDI_LOOKUP_RE = "(?i)\\$\\{(?:jndi:(?:ldap|rmi|dns)://|\\$?\\{?(?:lower|upper):j\\}ndi|::-j\\}ndi)";
export const _LEGACY_IPV4_PART_RE = "(?:0[xX][0-9a-fA-F]+|0[0-7]+|[1-9]\\d*|0)";
export const _LEGACY_IPV4_HOST_RE = "://(?:[^/@\\s]*@)?((?:0[xX][0-9a-fA-F]+|0[0-7]+|[1-9]\\d*|0)(?:\\.(?:0[xX][0-9a-fA-F]+|0[0-7]+|[1-9]\\d*|0)){0,3})(?=[:/\\s]|$)";
export const _LDAP_NULL_BYTE_TAIL_COMPILED = "\\*\\)+(?:%00|\\\\u0000|\\\\x00|\\\\0|\\x00)";
export const _LDAP_NULL_BYTE_DECODED_TAIL_COMPILED = "\\*\\)+\\x00";
export const _LDAP_NULL_BYTE_ATTR_COMPILED = "[a-zA-Z][\\w-]*\\s*=[\\d\\w\\s]*\\*\\)+(?:%00|\\\\u0000|\\\\x00|\\\\0|\\x00)";
export const _LDAP_NULL_BYTE_DECODED_ATTR_COMPILED = "[a-zA-Z][\\w-]*\\s*=[\\d\\w\\s]*\\*\\)+\\x00";
export const _LOG4SHELL_JNDI_LOOKUP_COMPILED = "(?i)\\$\\{(?:jndi:(?:ldap|rmi|dns)://|\\$?\\{?(?:lower|upper):j\\}ndi|::-j\\}ndi)";
export const _BARE_SHELL_PARAMETER_NAME_COMPILED = "\\A[A-Za-z_][A-Za-z0-9_]*(?:\\.[A-Za-z_][A-Za-z0-9_]*)*\\Z";
export const _FILE_UPLOAD_DANGEROUS_EXTENSIONS_SORTED: readonly string[] = ["phtml", "shtml", "asax", "ascx", "ashx", "asmx", "aspx", "bash", "jspx", "phar", "phps", "asa", "asp", "bat", "cer", "cfc", "cfm", "cgi", "cmd", "com", "exe", "hta", "jsp", "msi", "pht", "vbe", "vbs", "war", "wsf", "js", "pl", "py", "rb", "sh", "ws"];
export const _FILE_UPLOAD_DOUBLE_EXT_EXTENSIONS_SORTED: readonly string[] = ["phtml", "shtml", "asax", "ascx", "ashx", "asmx", "aspx", "bash", "jspx", "phar", "phps", "asa", "asp", "bat", "cer", "cfc", "cfm", "cgi", "cmd", "exe", "hta", "jsp", "msi", "pht", "vbe", "vbs", "war", "wsf", "js", "pl", "py", "rb", "sh", "ws"];
export const _FILE_UPLOAD_BENIGN_TERMINAL_SORTED: readonly string[] = ["docx", "jpeg", "pptx", "tiff", "webm", "webp", "xlsx", "avi", "bmp", "doc", "gif", "ico", "jpg", "mkv", "mov", "mp3", "mp4", "odt", "pdf", "png", "ppt", "svg", "tif", "wav", "xls"];

export const _LDAP_PAREN_CONJUNCTION_FOLLOWUP_SYMBOL_RE = "\\A\\s*(?:[!(]|\\*)";
export const _LDAP_PAREN_CONJUNCTION_FOLLOWUP_ATTR_RE = "\\A\\s*(?::)?(?:[a-zA-Z][\\w.-]*|\\d+(?:\\.\\d+)*)(?:;[\\w.-]+)*(?::[\\w.-]+)*\\s*:?=";
